name: CI

on:

  push:

   branches: [ "master" ]

 

jobs:

  build:



    runs-on: ubuntu-lates



    steps:

   

    - uses: actions/checkout@v3

    - uses: docker/login-action@v2.1.0

      with:



        login-server: taruncontainerregistry001.azurecr.io

        username: ${{ secrets.REGISTRY_USERNAME }}

        password: ${{ secrets.REGISTRY_PASSWORD }}



    - run: |

        docker build . -t taruncontainerregistry001.azurecr.io/bird:${{ github.sha }}

        docker push taruncontainerregistry001.azurecr.io/bird:${{ github.sha }}

       

    - name: Setup Kubectl

      uses: ThomasKliszowski/setup-kubectl@v1

     

    - uses: ThomasKliszowski/aks-set-context@v1

      with:

        creds: '${{ secrets.AZURE_CREDENTIALS }}'

        cluster-name: newaksforrunner

        resource-group: tarun_rg

       

       

    - uses: Azure/k8s-create-secret@v4

      with:

        container-registry-url: taruncontainerregistry001.azurecr.io

        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}

        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}

        secret-name: k8s-secret  

       

    - uses: Azure/k8s-deploy@v4.6

      with:

        manifests: |

          kube-manifests/deployment.yml

          kube-manifests/service.yml

        images: |

          taruncontainerregistry001.azurecr.io/bird:${{ github.sha }}

        imagepullsecrets: |

          k8s-secret
