name: CI

on:

  push:

   branches: [ "master" ]

 

jobs:

  build:



    runs-on: ubuntu-latest



    steps:

   

    - uses: actions/checkout@v3

      with:



        login-server: taruncontainerregistry11.azurecr.io

        username: ${{ secrets.REGISTRY_USERNAME }}

        password: ${{ secrets.REGISTRY_PASSWORD }}



    - run: |

        docker build . -t taruncontainerregistry11.azurecr.io/bird:${{ github.sha }}

        docker push taruncontainerregistry001.azurecr.io/bird:${{ github.sha }}

       

    - name: Setup Kubectl

      uses: setup-kubectl@v1

     

    - uses: aks-set-context@v1

      with:

        creds: '${{ secrets.AZURE_CREDENTIALS }}'

        cluster-name: tarunakscluster

        resource-group: tarun_rg

       

       

    - uses: k8s-create-secret@v1

      with:

        container-registry-url: taruncontainerregistry11.azurecr.io

        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}

        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}

        secret-name: k8s-secret  

       

    - uses: k8s-deploy@v1

      with:

        manifests: |

          kube-manifests/deployment.yml

          kube-manifests/service.yml

        images: |

          taruncontainerregistry11.azurecr.io/bird:${{ github.sha }}

        imagepullsecrets: |

          k8s-secret
